# Generated by Django 3.1.5 on 2021-01-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
